paths:
  data_dir: 'data'
  checkpoint_dir: '/tmp/checkpoints'
  log_dir: '/tmp/pitch_log'

audio:
  sample_rate: 22050
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  pitch_min: 50
  pitch_max: 500

training:
  n_val: 200
  batch_size: 32
  n_epochs: 1000

model:
  n_channels: 512